config/routes.rb
Rails.application.routes.draw do

  # devise_for :users

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :contacts do
    resources :numbers
  end
    
  root 'contacts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
    has_many :numbers, :dependent => :destroy
    accepts_nested_attributes_for :numbers, :allow_destroy => true
    validates :name, :presence => {message: "Name cannot be blank."}
    validates :user_id, :presence => true
   
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    before_action :authenticate_user!
    
    def index
        if current_user.role == "admin"
            @contact = Contact.all
        else
            @contact = Contact.where(user_id: current_user.id).order(created_at: :desc)
        end
    end

    def new
        @contact = Contact.new
        @contact.numbers.build
    end

    def edit
        @contact = Contact.find(params[:id])
    end

    def create
        @contact = Contact.new(contact_params)
        
        respond_to do |format|
            
            if @contact.save
                format.js
                redirect_to contacts_path
            else
                format.js
               
                
            end
        end
    end

    def update
        @contact = Contact.find(params[:id])
        # if @phonebook.update(contact_params)
            
        #     redirect_to contacts_path
        # else
        #     render 'edit'
        # end

        respond_to do |format|
            
            if @contact.update(contact_params)
                format.js { redirect_to contacts_path }
            else
                format.js
                
                #render 'edit'
            end
        end
    end

    def show
        @contact = Contact.find(params[:id])
    end

    def destroy
        @contact = Contact.find(params[:id])
        @contact.destroy
     
        redirect_to contacts_path
    end

    private
    def contact_params
        params.require(:contact).permit(:user_id, :name, numbers_attributes: [:id, :contact_id, :number, :_destroy])
    end
end

app/views/contacts/_form.html.erb
<%= form_with model: @contact do |form|%>
 
  <%= form.hidden_field :user_id, value: current_user.id %>
  
  <%= form.label :name %><br>
  <%= form.text_field :name, class: 'form-control' %>

  <%= form.fields_for :numbers do |builder| %>
    <%= render 'number_fields', :f => builder %>
  <% end %>

  <%= link_to_add_fields "+ More Number", form, :numbers %>
  
  <span id="helpBlock" class="help-block"></span>

  <p>
  <%= form.submit 'Submit', class: 'btn btn-primary btn-md btn-block' %>
  </p>

  


<% end %>

app/views/contacts/_number_fields.html.erb
<div class="fields">
  <p>
    <%= f.label :number, "Number" %>
    <%= f.text_field :number, class: 'form-control' %>
    <%= link_to_remove_fields "remove", f %><br />
  </p>
</div>

app/views/contacts/create.js.erb
//remove old validation messages
$(".notice").remove();
 
//display new validation messages
<% @contact.errors.each do |key, value| %>
    $("#helpBlock").append('<div class="notice"><%= escape_javascript(value)%></div>');
<% end %>

app/views/contacts/edit.html.erb
<% content_for :javascript_includes do %>
    <%= javascript_include_tag "contacts/edit" %>
<% end %>

<center><h1>Edit Contact</h1></center>
<%= render 'form' %>
<%= link_to 'Back', contacts_path, class: 'btn btn-default btn-md btn-block' %>

<span id="helpBlock" class="help-block"></span>

app/views/contacts/index.html.erb
<% if user_signed_in? %>
  <div class="row">
      <%= link_to '+ Add Contact', new_contact_path %> |
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  </div>

  <div class="row table-responsive">
    <table class="table table-bordered text-centered">
      <tr>
        <th class=col-md-1>No</th>
        <th class=col-md-4>Name</th>
        <th class=col-md-3>Options</th>
      </tr>

      <% no = 1 %>
      <% @contact.each do |contact| %>
        <tr>
          <td><%= no %></td>
          <td><%= contact.name %></td>
          <td>
          <%= link_to 'Show', contact, class: 'btn btn-info btn-xs' %>
            <%= link_to 'Edit', edit_contact_path(contact), class: 'btn btn-success btn-xs' %>
            <%= link_to 'Destroy', contact_path(contact), class: 'btn btn-danger btn-xs',
            method: :delete,
            data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
        <% no = no + 1 %>
      <% end %>
    </table>
  </div>

<!--p>User Id : <%= current_user.id %><p-->
<!--p>User Role : <%= current_user.role %></p-->
<% end %>
    

app/views/contacts/new.html.erb
<% content_for :javascript_includes do %>
    <%= javascript_include_tag "contacts/new" %>
<% end %>

<div class="row">
    <center><h1>New Contact</h1></center>
</div>

<%= render 'form' %>

<%= link_to 'Back', contacts_path, class: 'btn btn-default btn-md btn-block' %>

<span id="helpBlock" class="help-block"></span>

app/views/contacts/show.html.erb
<% if user_signed_in? %>

  <div class="row table-responsive">
    <table class="table table-bordered text-centered">
      <tr>
        <th>Number</th>
      </tr>

      <% for number in @contact.numbers %>
        <tr>
          <td><%= number.number %></td>
          <!--td>
            <%#= link_to 'Edit', edit_contact_number_path(:id => number.id, :contact_id => number.contact_id) , class: 'btn btn-success btn-xs' %>
            <%#= link_to 'Delete', contact_number_path(:id => number.id, :contact_id => number.contact_id) , class: 'btn btn-danger btn-xs',
            method: :delete,
            data: { confirm: 'Are you sure?' } %>
          </td-->
        </tr>
      <% end %>
    </table>
  </div>

<!--p>User Id : <%= current_user.id %><p-->
<!--p>User Role : <%= current_user.role %></p-->
<% end %>

app/views/contacts/update.js.erb
//remove old validation messages
$(".notice").remove();
 
//display new validation messages
<% @contact.errors.each do |key, value| %>
    $("#helpBlock").append('<div class="notice"><%= escape_javascript(value)%></div>');
<% end %>